### ISSUE TITLE
There is a problem with right clicking the navigation bar

### ISSUE THREAD

**Issue by Createwj** [zhou-tao/vue-power-admin#11]
### Describe the bug

![image](https://user-images.githubusercontent.com/24564508/236373868-3646bee6-b1b4-415c-b6fe-67fb2cd6b079.png)

### System Info

<img width="268" alt="image" src="https://user-images.githubusercontent.com/24564508/236374112-6aaf8c31-ee31-4e1e-9706-1d09bfcf3ed2.png">

### Validations

- [X] Check that there isn't [already an issue](https://github.com/zhou-tao/vue-power-admin/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/zhou-tao/vue-power-admin/discussions).

**Comment by Createwj** [comment]
The right click also triggered the click effect

**Comment by Createwj** [comment]
![image](https://user-images.githubusercontent.com/24564508/236374855-3535424f-86b7-471f-892d-1234d6078b26.png)
### so there's a bug.

**Comment by zhou-tao** [comment]
> ![image](https://user-images.githubusercontent.com/24564508/236374855-3535424f-86b7-471f-892d-1234d6078b26.png)
> 
> ### so there's a bug.

It seems that Google Chrome remembers the password to cause it.

**Comment by Blackman99** [comment]
The fix PR: #14
